CREATE TABLE company (
    id VARCHAR(27) PRIMARY KEY,
    kode VARCHAR(5) UNIQUE NOT NULL,
    nama TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ
);

INSERT INTO company (id, kode, nama) VALUES
('3SRlQ8zX9vJ2mN5P6Q7R8S9T001', 'IPSR', 'PT Inti Pelantas Kawan');
