CREATE TABLE users (
    id VARCHAR(27) PRIMARY KEY,
    email TEXT UNIQUE,
    role_system TEXT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ
);


